name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'PHPStan'
                        run: composer phpstan
                    -
                        name: 'Coding Standard'
                        run: composer check-cs

                    -
                        name: 'Check Active Classes'
                        run: vendor/bin/easy-ci check-active-class app src config --ansi

                    -
                        name: 'Laravel Console'
                        run: php artisan --ansi

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v2"

            -   run: ${{ matrix.actions.run }}
