name: Unit Tests

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    unit_tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v2"

            # for controller tests
            -   run: vendor/bin/phpunit
